### ISSUE TITLE
“主题已更换”的判断依据是什么？

### ISSUE THREAD

**Issue by ding113** [solstice23/argon-theme-showcase#13]
作为唯一一个被判断为“主题已更换”的网站，我想请问下出现这一问题是什么原因导致的
我目前使用的就是最新版的 Argon Theme ，而且主题文件我是没有改过的～

URL：https://www.ygxz.in

**Comment by solstice23** [comment]
检测如下关键字
https://github.com/solstice23/argon-theme-showcase/blob/aaca7dbbd226c2d268ec75d9175822c5d3636612/scripts/update-site-status.js#L6-L14

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/158558075-f0251ca6-724d-4df7-a07a-33619af5cdfb.png)

奇怪，我本地跑都可以通过的

**Comment by ding113** [comment]
也许是我服务器不稳定？
我这里也是可以通过的，而且我看机器人的状态也是改了好几次

**Comment by solstice23** [comment]
https://argon-showcase.solstice23.top/
似乎好了

**Comment by Jiaocz** [comment]
现在我的站点页显示了主题已更换，但是我自己测试关键字都是有的
`blog.orangii.cn`
😶
