### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by Andy17269** [solstice23/argon-theme-showcase#57]
为什么白名单开了，网站日志也显示Argon Robot访问了却显示无法访问？
日志如下：
20.237.196.35 - - [02/May/2022:12:57:31 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75"
20.237.196.35 - - [02/May/2022:12:57:33 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75"
20.237.196.35 - - [02/May/2022:12:57:36 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75"
20.237.196.35 - - [02/May/2022:12:57:37 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75"
20.237.196.35 - - [02/May/2022:12:57:39 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75"
20.237.196.35 - - [02/May/2022:12:57:42 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75"
20.237.196.35 - - [02/May/2022:12:57:42 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75"
20.237.196.35 - - [02/May/2022:12:57:44 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75"

20.231.109.51 - - [01/May/2022:16:25:57 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75"
20.231.109.51 - - [01/May/2022:16:25:59 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75"
20.231.109.51 - - [01/May/2022:16:26:03 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75"
20.231.109.51 - - [01/May/2022:16:26:04 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75"
20.231.109.51 - - [01/May/2022:16:26:06 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75"

**Comment by BA7JCM** [comment]
> 为什么白名单开了，网站日志也显示Argon Robot访问了却显示无法访问？ 日志如下： 20.237.196.35 - - [02/May/2022:12:57:31 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75" 20.237.196.35 - - [02/May/2022:12:57:33 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75" 20.237.196.35 - - [02/May/2022:12:57:36 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75" 20.237.196.35 - - [02/May/2022:12:57:37 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75" 20.237.196.35 - - [02/May/2022:12:57:39 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75" 20.237.196.35 - - [02/May/2022:12:57:42 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75" 20.237.196.35 - - [02/May/2022:12:57:42 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75" 20.237.196.35 - - [02/May/2022:12:57:44 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75"
> 
> 20.231.109.51 - - [01/May/2022:16:25:57 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75" 20.231.109.51 - - [01/May/2022:16:25:59 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75" 20.231.109.51 - - [01/May/2022:16:26:03 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75" 20.231.109.51 - - [01/May/2022:16:26:04 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75" 20.231.109.51 - - [01/May/2022:16:26:06 +0800] "GET / HTTP/1.1" 444 0 "-" "ArgonBot df1c3f714b528c75"

看起来像是宝塔waf干的

**Comment by Andy17269** [comment]
奥
